[package]
name = "test-build-protos"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
femtopb = { version = "0.1.0", path = "../.." }

[build-dependencies]
anyhow = "1.0.81"
femtopb-build = { version = "0.1.0", path = "../../build" }
