name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
    - name: Check for panics in release builds
      run: cargo build --package test-build-protos --features assert-no-panic --release
    - name: Check for defmt end-to-end support
      run: cargo build --package test-build-protos --features defmt
